# Generated by Django 6.0.3 on 2026-06-15 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stars', models.IntegerField(default=3)),
                ('wifi', models.BooleanField(default=True)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='destinations.destination')),
            ],
        ),
    ]
