# Generated by Django 6.0.3 on 2026-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
